FROM httpd

RUN sed -i \
        -e 's/^#\(Include .*httpd-ssl.conf\)/\1/' \
        -e 's/^#\(LoadModule .*mod_ssl.so\)/\1/' \
        -e 's/^#\(LoadModule .*mod_socache_shmcb.so\)/\1/' \
        conf/httpd.conf

ADD server.crt /usr/local/apache2/conf/
ADD server.key /usr/local/apache2/conf/


EXPOSE 443
